# Generated by Django 3.2.3 on 2021-05-20 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_name', models.CharField(blank=True, max_length=50)),
                ('keyword_eng_name', models.CharField(max_length=50)),
                ('keyword_count', models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('eng_name', models.CharField(max_length=50)),
                ('profile_path', models.CharField(max_length=200)),
                ('gender', models.IntegerField()),
                ('job', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('original_title', models.CharField(max_length=50)),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('poster_path', models.CharField(max_length=200)),
                ('backdrop_path', models.CharField(max_length=200)),
                ('runtime', models.IntegerField(default=0)),
                ('actors', models.ManyToManyField(related_name='movie_actor', to='movies.Person')),
                ('directors', models.ManyToManyField(related_name='movie_director', to='movies.Person')),
                ('genres', models.ManyToManyField(to='movies.Genre')),
                ('hates', models.ManyToManyField(related_name='hate_movies', to=settings.AUTH_USER_MODEL)),
                ('keywords', models.ManyToManyField(to='movies.Keyword')),
                ('likes', models.ManyToManyField(related_name='like_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
