# Generated by Django 3.2.3 on 2021-05-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210521_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='keywords',
            field=models.ManyToManyField(related_name='movie_keywords', to='movies.Keyword'),
        ),
    ]
